[project]
name = "mnist"
version = "1.0.0"
description = "A simple MNIST digit classifier using PyTorch."
requires-python = ">=3.13"
dependencies = ["torch", "torchvision", "matplotlib"]

[tool.ruff]
line-length = 120
