main.exe: BubbleSort.c HeapSort.c InsertionSort.c MergeSort.c QuickSort.c RadixSort.c SelectionSort.c ShellSort.c main.c
	gcc BubbleSort.c HeapSort.c InsertionSort.c MergeSort.c QuickSort.c RadixSort.c SelectionSort.c ShellSort.c main.c -o main.exe

clean:
	rm -f *.o *.exe
