main.exe: bubble_sort.c heap_sort.c insertion_sort.c merge_sort.c quick_sort.c radix_sort.c selection_sort.c shell_sort.c main.c
	gcc -Wall bubble_sort.c heap_sort.c insertion_sort.c merge_sort.c quick_sort.c radix_sort.c selection_sort.c shell_sort.c main.c -o main.exe

clean:
	rm -f *.o *.exe
